name: Programming Joke Collector

on:
  schedule:
    - cron: '0 8-20 * * 0-4' # Sun-Thu, 8AM-8PM UTC
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  collect-joke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config --global user.name "dipu0"
          git config --global user.email "c.dipu0@gmail.com"

      - name: Initialize Docs
        run: |
          mkdir -p docs
          cat > docs/_config.yml <<EOF
          title: DevJokesDaily
          theme: jekyll-theme-primer
          plugins:
            - jekyll-relative-links
          exclude:
            - README.md
          EOF

          cat > docs/index.md <<EOF
          ---
          layout: default
          ---
          # DevJokesDaily
          
          Welcome to the programming joke archive!
          
          {% for month in site.jokes %}
          - [{{ month.name | remove: ".md" }}]({{ month.url }})
          {% endfor %}
          EOF

      - name: Collect Joke
        run: |
          MONTH=$(date +'%Y-%m')
          mkdir -p docs/jokes
          JOKE_FILE="docs/jokes/$MONTH.md"
          
          # Initialize file if needed
          [ -f "$JOKE_FILE" ] || echo "# $MONTH Jokes" > "$JOKE_FILE"

          # Get joke
          JOKE=$(curl -s "https://v2.jokeapi.dev/joke/Programming?blacklistFlags=nsfw,racist&type=single,twopart")
          if jq -e '.type == "twopart"' <<< "$JOKE"; then
            CONTENT="**Q:** $(jq -r '.setup' <<< "$JOKE")\n**A:** $(jq -r '.delivery' <<< "$JOKE")"
          else
            CONTENT=$(jq -r '.joke' <<< "$JOKE")
          fi

          # Append joke
          echo -e "\n### $(date +'%Y-%m-%d %H:%M')\n$CONTENT" >> "$JOKE_FILE"
          
          # Commit
          git add docs/
          git commit -m "Added new joke" || echo "No changes to commit"
          git push

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3