name: Programming Joke Collector
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 8-20 * * 0-4' # Sun-Thu, 8AM-8PM UTC
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  setup-and-collect-joke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "dipu0"
          git config --global user.email "c.dipu0@gmail.com"
          git config --global pull.rebase true

      - name: Create GitHub Pages Project Structure
        run: |
          # Ensure docs directory exists
          mkdir -p docs/jokes
          mkdir -p docs/assets/css

          # Create _config.yml
          cat > docs/_config.yml << EOF
title: DevJokesDaily
description: A daily collection of programming jokes
theme: jekyll-theme-primer
plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
EOF

          # Create main index.md
          cat > docs/index.md << EOF
---
layout: default
title: DevJokesDaily
---
# Programming Joke Archive

Welcome to the daily dose of developer humor! 

## Monthly Joke Collections
EOF

          # Create README.md
          cat > docs/README.md << EOF
# DevJokesDaily

A collection of programming jokes, updated daily.

## Joke Collections
EOF

          # Create assets/css/style.scss
          cat > docs/assets/css/style.scss << EOF
---
---

@import "{{ site.theme }}";

body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
  line-height: 1.6;
  max-width: 800px;
  margin: 0 auto;
  padding: 20px;
}

.joke {
  background-color: #f4f4f4;
  border-left: 4px solid #007bff;
  padding: 10px;
  margin: 10px 0;
}
EOF

          # Create .gitignore to prevent Jekyll build artifacts from being tracked
          cat > .gitignore << EOF
docs/_site/
docs/.sass-cache/
docs/.jekyll-cache/
docs/.jekyll-metadata
EOF

      - name: Determine Run Conditions
        id: schedule
        run: |
          SHOULD_RUN="true"
          DAY=$(date +%u)
          if [[ $DAY -ge 5 ]]; then
            [[ $(( RANDOM % 100 )) -gt 30 ]] && SHOULD_RUN="false"
          fi
          echo "should_run=$SHOULD_RUN" >> $GITHUB_OUTPUT
          echo "date=$(date +'%Y-%m-%d %H:%M')" >> $GITHUB_OUTPUT

      - name: Collect Initial Joke
        if: steps.schedule.outputs.should_run == 'true'
        run: |
          MONTH=$(date +'%Y-%m')
          JOKE_FILE="docs/jokes/$MONTH.md"
          
          # Initialize monthly file
          printf "# %s Jokes\n\n" "$MONTH" > "$JOKE_FILE"
          
          # Fetch joke
          JOKE_JSON=$(curl -s "https://v2.jokeapi.dev/joke/Programming?blacklistFlags=nsfw,racist&type=single,twopart")
          
          if jq -e '.type == "twopart"' <<< "$JOKE_JSON"; then
            CONTENT="**Q:** $(jq -r '.setup' <<< "$JOKE_JSON")\n**A:** $(jq -r '.delivery' <<< "$JOKE_JSON")"
            MSG="Joke #$(jq -r '.id' <<< "$JOKE_JSON"): $(jq -r '.setup' <<< "$JOKE_JSON" | head -n 1)"
          else
            CONTENT=$(jq -r '.joke' <<< "$JOKE_JSON")
            MSG="Joke #$(jq -r '.id' <<< "$JOKE_JSON"): ${CONTENT:0:50}"
          fi
          
          # Save joke
          echo -e "\n### $(steps.schedule.outputs.date) (ID: $(jq -r '.id' <<< "$JOKE_JSON"))\n$CONTENT" >> "$JOKE_FILE"
          
          # Update indexes
          echo "- [$MONTH](jokes/$MONTH.md)" >> docs/index.md
          echo "- [$MONTH](jokes/$MONTH.md)" >> docs/README.md

      - name: Commit Changes
        run: |
          git add docs/ .gitignore
          git commit -m "Initial GitHub Pages setup with first programming joke" || echo "No changes to commit"
          git push

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
